name: Build and Upload
on:
  workflow_dispatch:
  push:

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build
        run: |
          cd ${{ GITHUB.WORKSPACE }}
          make all
